# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1bcf5d19249f9cdbba2f48235dc642fd1114ce84f0420dce1ba9dfb13015e2b1b71128f3ade4e08bb3d9dc8442cf01f84f68dbeaeb5db23565f8315d062b60d

test:
  secret_key_base: 979926a0fb4c49f017c1e8ae0184ba0d4d5fc773eef6c46d693afe7e7d3359f2dbdc9b37702451dd1887ef2bdec076518220d1fc18dfdfc3567570f5bb833a77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
