source 'https://rubygems.org'

gem 'rails', '~>5.0.1'
gem 'sass-rails'
gem 'uglifier', '>= 1.3.0'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'jbuilder', '~> 1.2'
gem 'pg'
gem 'bcrypt'

group :doc do
  gem 'sdoc', require: false
end

group :test do
  gem 'factory_girl_rails'
  gem 'shoulda-matchers'
  gem 'faker'
  gem 'capybara'
  gem 'guard-rspec'
  gem 'launchy'
end

group :development, :test do
  gem 'rspec-rails'
  gem 'byebug'
end

gem 'newrelic_rpm'
